// Generated by gencpp from file roborts_msgs/RobotHeat.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_ROBOTHEAT_H
#define ROBORTS_MSGS_MESSAGE_ROBOTHEAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct RobotHeat_
{
  typedef RobotHeat_<ContainerAllocator> Type;

  RobotHeat_()
    : chassis_volt(0)
    , chassis_current(0)
    , chassis_power(0.0)
    , chassis_power_buffer(0)
    , shooter_heat(0)  {
    }
  RobotHeat_(const ContainerAllocator& _alloc)
    : chassis_volt(0)
    , chassis_current(0)
    , chassis_power(0.0)
    , chassis_power_buffer(0)
    , shooter_heat(0)  {
  (void)_alloc;
    }



   typedef uint16_t _chassis_volt_type;
  _chassis_volt_type chassis_volt;

   typedef uint16_t _chassis_current_type;
  _chassis_current_type chassis_current;

   typedef double _chassis_power_type;
  _chassis_power_type chassis_power;

   typedef uint16_t _chassis_power_buffer_type;
  _chassis_power_buffer_type chassis_power_buffer;

   typedef uint16_t _shooter_heat_type;
  _shooter_heat_type shooter_heat;





  typedef boost::shared_ptr< ::roborts_msgs::RobotHeat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::RobotHeat_<ContainerAllocator> const> ConstPtr;

}; // struct RobotHeat_

typedef ::roborts_msgs::RobotHeat_<std::allocator<void> > RobotHeat;

typedef boost::shared_ptr< ::roborts_msgs::RobotHeat > RobotHeatPtr;
typedef boost::shared_ptr< ::roborts_msgs::RobotHeat const> RobotHeatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::RobotHeat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::RobotHeat_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/dengxin/icra2020/devel/share/roborts_msgs/msg', '/home/dengxin/icra2020/src/RoboRTS-ros/roborts_msgs/msg', '/home/dengxin/icra2020/src/RoboRTS-ros/roborts_msgs/msg/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::RobotHeat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::RobotHeat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::RobotHeat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12a69f2d33ac7367772428034e998f18";
  }

  static const char* value(const ::roborts_msgs::RobotHeat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12a69f2d33ac7367ULL;
  static const uint64_t static_value2 = 0x772428034e998f18ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/RobotHeat";
  }

  static const char* value(const ::roborts_msgs::RobotHeat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#robot power and heat data\n\
uint16 chassis_volt\n\
uint16 chassis_current\n\
float64  chassis_power\n\
uint16 chassis_power_buffer\n\
uint16 shooter_heat\n\
\n\
";
  }

  static const char* value(const ::roborts_msgs::RobotHeat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chassis_volt);
      stream.next(m.chassis_current);
      stream.next(m.chassis_power);
      stream.next(m.chassis_power_buffer);
      stream.next(m.shooter_heat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotHeat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::RobotHeat_<ContainerAllocator>& v)
  {
    s << indent << "chassis_volt: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.chassis_volt);
    s << indent << "chassis_current: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.chassis_current);
    s << indent << "chassis_power: ";
    Printer<double>::stream(s, indent + "  ", v.chassis_power);
    s << indent << "chassis_power_buffer: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.chassis_power_buffer);
    s << indent << "shooter_heat: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.shooter_heat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_ROBOTHEAT_H
