// Generated by gencpp from file icra_nav/c_start_end_srvRequest.msg
// DO NOT EDIT!


#ifndef ICRA_NAV_MESSAGE_C_START_END_SRVREQUEST_H
#define ICRA_NAV_MESSAGE_C_START_END_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace icra_nav
{
template <class ContainerAllocator>
struct c_start_end_srvRequest_
{
  typedef c_start_end_srvRequest_<ContainerAllocator> Type;

  c_start_end_srvRequest_()
    : flPathStartX(0.0)
    , flPathStartY(0.0)
    , flPathEndX(0.0)
    , flPathEndY(0.0)
    , vfConstraintPositionX()
    , vfConstraintPositionY()
    , flConstraintVelocity(0.0)  {
    }
  c_start_end_srvRequest_(const ContainerAllocator& _alloc)
    : flPathStartX(0.0)
    , flPathStartY(0.0)
    , flPathEndX(0.0)
    , flPathEndY(0.0)
    , vfConstraintPositionX(_alloc)
    , vfConstraintPositionY(_alloc)
    , flConstraintVelocity(0.0)  {
  (void)_alloc;
    }



   typedef float _flPathStartX_type;
  _flPathStartX_type flPathStartX;

   typedef float _flPathStartY_type;
  _flPathStartY_type flPathStartY;

   typedef float _flPathEndX_type;
  _flPathEndX_type flPathEndX;

   typedef float _flPathEndY_type;
  _flPathEndY_type flPathEndY;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _vfConstraintPositionX_type;
  _vfConstraintPositionX_type vfConstraintPositionX;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _vfConstraintPositionY_type;
  _vfConstraintPositionY_type vfConstraintPositionY;

   typedef float _flConstraintVelocity_type;
  _flConstraintVelocity_type flConstraintVelocity;





  typedef boost::shared_ptr< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct c_start_end_srvRequest_

typedef ::icra_nav::c_start_end_srvRequest_<std::allocator<void> > c_start_end_srvRequest;

typedef boost::shared_ptr< ::icra_nav::c_start_end_srvRequest > c_start_end_srvRequestPtr;
typedef boost::shared_ptr< ::icra_nav::c_start_end_srvRequest const> c_start_end_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace icra_nav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'icra_nav': ['/home/dengxin/icra2020/src/icra_nav/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88f1f4545b684e624f61ddcb593a90fa";
  }

  static const char* value(const ::icra_nav::c_start_end_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88f1f4545b684e62ULL;
  static const uint64_t static_value2 = 0x4f61ddcb593a90faULL;
};

template<class ContainerAllocator>
struct DataType< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_nav/c_start_end_srvRequest";
  }

  static const char* value(const ::icra_nav::c_start_end_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 flPathStartX\n\
float32 flPathStartY\n\
float32 flPathEndX\n\
float32 flPathEndY\n\
float32[] vfConstraintPositionX\n\
float32[] vfConstraintPositionY\n\
float32 flConstraintVelocity\n\
";
  }

  static const char* value(const ::icra_nav::c_start_end_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flPathStartX);
      stream.next(m.flPathStartY);
      stream.next(m.flPathEndX);
      stream.next(m.flPathEndY);
      stream.next(m.vfConstraintPositionX);
      stream.next(m.vfConstraintPositionY);
      stream.next(m.flConstraintVelocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct c_start_end_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icra_nav::c_start_end_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icra_nav::c_start_end_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "flPathStartX: ";
    Printer<float>::stream(s, indent + "  ", v.flPathStartX);
    s << indent << "flPathStartY: ";
    Printer<float>::stream(s, indent + "  ", v.flPathStartY);
    s << indent << "flPathEndX: ";
    Printer<float>::stream(s, indent + "  ", v.flPathEndX);
    s << indent << "flPathEndY: ";
    Printer<float>::stream(s, indent + "  ", v.flPathEndY);
    s << indent << "vfConstraintPositionX[]" << std::endl;
    for (size_t i = 0; i < v.vfConstraintPositionX.size(); ++i)
    {
      s << indent << "  vfConstraintPositionX[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vfConstraintPositionX[i]);
    }
    s << indent << "vfConstraintPositionY[]" << std::endl;
    for (size_t i = 0; i < v.vfConstraintPositionY.size(); ++i)
    {
      s << indent << "  vfConstraintPositionY[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vfConstraintPositionY[i]);
    }
    s << indent << "flConstraintVelocity: ";
    Printer<float>::stream(s, indent + "  ", v.flConstraintVelocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICRA_NAV_MESSAGE_C_START_END_SRVREQUEST_H
