// Generated by gencpp from file icra_nav/path_srvResponse.msg
// DO NOT EDIT!


#ifndef ICRA_NAV_MESSAGE_PATH_SRVRESPONSE_H
#define ICRA_NAV_MESSAGE_PATH_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace icra_nav
{
template <class ContainerAllocator>
struct path_srvResponse_
{
  typedef path_srvResponse_<ContainerAllocator> Type;

  path_srvResponse_()
    : boSuccess(false)  {
    }
  path_srvResponse_(const ContainerAllocator& _alloc)
    : boSuccess(false)  {
  (void)_alloc;
    }



   typedef uint8_t _boSuccess_type;
  _boSuccess_type boSuccess;





  typedef boost::shared_ptr< ::icra_nav::path_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icra_nav::path_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct path_srvResponse_

typedef ::icra_nav::path_srvResponse_<std::allocator<void> > path_srvResponse;

typedef boost::shared_ptr< ::icra_nav::path_srvResponse > path_srvResponsePtr;
typedef boost::shared_ptr< ::icra_nav::path_srvResponse const> path_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icra_nav::path_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icra_nav::path_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace icra_nav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'icra_nav': ['/home/dengxin/icra2020/src/icra_nav/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::icra_nav::path_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icra_nav::path_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_nav::path_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_nav::path_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_nav::path_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_nav::path_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icra_nav::path_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eca856ee71f824332e753aaa50c58161";
  }

  static const char* value(const ::icra_nav::path_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeca856ee71f82433ULL;
  static const uint64_t static_value2 = 0x2e753aaa50c58161ULL;
};

template<class ContainerAllocator>
struct DataType< ::icra_nav::path_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_nav/path_srvResponse";
  }

  static const char* value(const ::icra_nav::path_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icra_nav::path_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool boSuccess\n\
";
  }

  static const char* value(const ::icra_nav::path_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icra_nav::path_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.boSuccess);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct path_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icra_nav::path_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icra_nav::path_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "boSuccess: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.boSuccess);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICRA_NAV_MESSAGE_PATH_SRVRESPONSE_H
