// Generated by gencpp from file icra_nav/path_srvRequest.msg
// DO NOT EDIT!


#ifndef ICRA_NAV_MESSAGE_PATH_SRVREQUEST_H
#define ICRA_NAV_MESSAGE_PATH_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace icra_nav
{
template <class ContainerAllocator>
struct path_srvRequest_
{
  typedef path_srvRequest_<ContainerAllocator> Type;

  path_srvRequest_()
    : vfPathPositionX()
    , vfPathPositionY()
    , viPathIndex()  {
    }
  path_srvRequest_(const ContainerAllocator& _alloc)
    : vfPathPositionX(_alloc)
    , vfPathPositionY(_alloc)
    , viPathIndex(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _vfPathPositionX_type;
  _vfPathPositionX_type vfPathPositionX;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _vfPathPositionY_type;
  _vfPathPositionY_type vfPathPositionY;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _viPathIndex_type;
  _viPathIndex_type viPathIndex;





  typedef boost::shared_ptr< ::icra_nav::path_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icra_nav::path_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct path_srvRequest_

typedef ::icra_nav::path_srvRequest_<std::allocator<void> > path_srvRequest;

typedef boost::shared_ptr< ::icra_nav::path_srvRequest > path_srvRequestPtr;
typedef boost::shared_ptr< ::icra_nav::path_srvRequest const> path_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icra_nav::path_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icra_nav::path_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace icra_nav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'icra_nav': ['/home/dengxin/icra2020/src/icra_nav/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::icra_nav::path_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icra_nav::path_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_nav::path_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_nav::path_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_nav::path_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_nav::path_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icra_nav::path_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e2339f584c26947579f6b280c3d715f";
  }

  static const char* value(const ::icra_nav::path_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e2339f584c26947ULL;
  static const uint64_t static_value2 = 0x579f6b280c3d715fULL;
};

template<class ContainerAllocator>
struct DataType< ::icra_nav::path_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_nav/path_srvRequest";
  }

  static const char* value(const ::icra_nav::path_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icra_nav::path_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] vfPathPositionX\n\
float32[] vfPathPositionY\n\
uint32[] viPathIndex\n\
";
  }

  static const char* value(const ::icra_nav::path_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icra_nav::path_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vfPathPositionX);
      stream.next(m.vfPathPositionY);
      stream.next(m.viPathIndex);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct path_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icra_nav::path_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icra_nav::path_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "vfPathPositionX[]" << std::endl;
    for (size_t i = 0; i < v.vfPathPositionX.size(); ++i)
    {
      s << indent << "  vfPathPositionX[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vfPathPositionX[i]);
    }
    s << indent << "vfPathPositionY[]" << std::endl;
    for (size_t i = 0; i < v.vfPathPositionY.size(); ++i)
    {
      s << indent << "  vfPathPositionY[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vfPathPositionY[i]);
    }
    s << indent << "viPathIndex[]" << std::endl;
    for (size_t i = 0; i < v.viPathIndex.size(); ++i)
    {
      s << indent << "  viPathIndex[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.viPathIndex[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICRA_NAV_MESSAGE_PATH_SRVREQUEST_H
