// Generated by gencpp from file icra_nav/path_vector.msg
// DO NOT EDIT!


#ifndef ICRA_NAV_MESSAGE_PATH_VECTOR_H
#define ICRA_NAV_MESSAGE_PATH_VECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace icra_nav
{
template <class ContainerAllocator>
struct path_vector_
{
  typedef path_vector_<ContainerAllocator> Type;

  path_vector_()
    : vfPositionX()
    , vfPositionY()  {
    }
  path_vector_(const ContainerAllocator& _alloc)
    : vfPositionX(_alloc)
    , vfPositionY(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _vfPositionX_type;
  _vfPositionX_type vfPositionX;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _vfPositionY_type;
  _vfPositionY_type vfPositionY;





  typedef boost::shared_ptr< ::icra_nav::path_vector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icra_nav::path_vector_<ContainerAllocator> const> ConstPtr;

}; // struct path_vector_

typedef ::icra_nav::path_vector_<std::allocator<void> > path_vector;

typedef boost::shared_ptr< ::icra_nav::path_vector > path_vectorPtr;
typedef boost::shared_ptr< ::icra_nav::path_vector const> path_vectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icra_nav::path_vector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icra_nav::path_vector_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace icra_nav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'icra_nav': ['/home/dengxin/icra2020/src/icra_nav/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::icra_nav::path_vector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icra_nav::path_vector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_nav::path_vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_nav::path_vector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_nav::path_vector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_nav::path_vector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icra_nav::path_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e633e5e50a58ce55b89c873561d948a7";
  }

  static const char* value(const ::icra_nav::path_vector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe633e5e50a58ce55ULL;
  static const uint64_t static_value2 = 0xb89c873561d948a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::icra_nav::path_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_nav/path_vector";
  }

  static const char* value(const ::icra_nav::path_vector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icra_nav::path_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] vfPositionX\n\
float32[] vfPositionY\n\
";
  }

  static const char* value(const ::icra_nav::path_vector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icra_nav::path_vector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vfPositionX);
      stream.next(m.vfPositionY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct path_vector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icra_nav::path_vector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icra_nav::path_vector_<ContainerAllocator>& v)
  {
    s << indent << "vfPositionX[]" << std::endl;
    for (size_t i = 0; i < v.vfPositionX.size(); ++i)
    {
      s << indent << "  vfPositionX[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vfPositionX[i]);
    }
    s << indent << "vfPositionY[]" << std::endl;
    for (size_t i = 0; i < v.vfPositionY.size(); ++i)
    {
      s << indent << "  vfPositionY[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vfPositionY[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICRA_NAV_MESSAGE_PATH_VECTOR_H
