// Generated by gencpp from file icra_nav/punish.msg
// DO NOT EDIT!


#ifndef ICRA_NAV_MESSAGE_PUNISH_H
#define ICRA_NAV_MESSAGE_PUNISH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace icra_nav
{
template <class ContainerAllocator>
struct punish_
{
  typedef punish_<ContainerAllocator> Type;

  punish_()
    : viPunishAreas()  {
    }
  punish_(const ContainerAllocator& _alloc)
    : viPunishAreas(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _viPunishAreas_type;
  _viPunishAreas_type viPunishAreas;





  typedef boost::shared_ptr< ::icra_nav::punish_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icra_nav::punish_<ContainerAllocator> const> ConstPtr;

}; // struct punish_

typedef ::icra_nav::punish_<std::allocator<void> > punish;

typedef boost::shared_ptr< ::icra_nav::punish > punishPtr;
typedef boost::shared_ptr< ::icra_nav::punish const> punishConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icra_nav::punish_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icra_nav::punish_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace icra_nav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'icra_nav': ['/home/dengxin/icra2020/src/icra_nav/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::icra_nav::punish_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icra_nav::punish_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_nav::punish_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_nav::punish_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_nav::punish_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_nav::punish_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icra_nav::punish_<ContainerAllocator> >
{
  static const char* value()
  {
    return "901ef32caa07726292504b26e2c68f0d";
  }

  static const char* value(const ::icra_nav::punish_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x901ef32caa077262ULL;
  static const uint64_t static_value2 = 0x92504b26e2c68f0dULL;
};

template<class ContainerAllocator>
struct DataType< ::icra_nav::punish_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_nav/punish";
  }

  static const char* value(const ::icra_nav::punish_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icra_nav::punish_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] viPunishAreas\n\
";
  }

  static const char* value(const ::icra_nav::punish_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icra_nav::punish_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.viPunishAreas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct punish_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icra_nav::punish_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icra_nav::punish_<ContainerAllocator>& v)
  {
    s << indent << "viPunishAreas[]" << std::endl;
    for (size_t i = 0; i < v.viPunishAreas.size(); ++i)
    {
      s << indent << "  viPunishAreas[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.viPunishAreas[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICRA_NAV_MESSAGE_PUNISH_H
