// Generated by gencpp from file icra_nav/start_end_point.msg
// DO NOT EDIT!


#ifndef ICRA_NAV_MESSAGE_START_END_POINT_H
#define ICRA_NAV_MESSAGE_START_END_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace icra_nav
{
template <class ContainerAllocator>
struct start_end_point_
{
  typedef start_end_point_<ContainerAllocator> Type;

  start_end_point_()
    : flStartX(0.0)
    , flStartY(0.0)
    , flEndX(0.0)
    , flEndY(0.0)  {
    }
  start_end_point_(const ContainerAllocator& _alloc)
    : flStartX(0.0)
    , flStartY(0.0)
    , flEndX(0.0)
    , flEndY(0.0)  {
  (void)_alloc;
    }



   typedef float _flStartX_type;
  _flStartX_type flStartX;

   typedef float _flStartY_type;
  _flStartY_type flStartY;

   typedef float _flEndX_type;
  _flEndX_type flEndX;

   typedef float _flEndY_type;
  _flEndY_type flEndY;





  typedef boost::shared_ptr< ::icra_nav::start_end_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icra_nav::start_end_point_<ContainerAllocator> const> ConstPtr;

}; // struct start_end_point_

typedef ::icra_nav::start_end_point_<std::allocator<void> > start_end_point;

typedef boost::shared_ptr< ::icra_nav::start_end_point > start_end_pointPtr;
typedef boost::shared_ptr< ::icra_nav::start_end_point const> start_end_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icra_nav::start_end_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icra_nav::start_end_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace icra_nav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'icra_nav': ['/home/dengxin/icra2020/src/icra_nav/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::icra_nav::start_end_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icra_nav::start_end_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_nav::start_end_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_nav::start_end_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_nav::start_end_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_nav::start_end_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icra_nav::start_end_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b46825f0775aab6934c6297120354ac";
  }

  static const char* value(const ::icra_nav::start_end_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b46825f0775aab6ULL;
  static const uint64_t static_value2 = 0x934c6297120354acULL;
};

template<class ContainerAllocator>
struct DataType< ::icra_nav::start_end_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_nav/start_end_point";
  }

  static const char* value(const ::icra_nav::start_end_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icra_nav::start_end_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 flStartX\n\
float32 flStartY\n\
float32 flEndX\n\
float32 flEndY\n\
";
  }

  static const char* value(const ::icra_nav::start_end_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icra_nav::start_end_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flStartX);
      stream.next(m.flStartY);
      stream.next(m.flEndX);
      stream.next(m.flEndY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct start_end_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icra_nav::start_end_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icra_nav::start_end_point_<ContainerAllocator>& v)
  {
    s << indent << "flStartX: ";
    Printer<float>::stream(s, indent + "  ", v.flStartX);
    s << indent << "flStartY: ";
    Printer<float>::stream(s, indent + "  ", v.flStartY);
    s << indent << "flEndX: ";
    Printer<float>::stream(s, indent + "  ", v.flEndX);
    s << indent << "flEndY: ";
    Printer<float>::stream(s, indent + "  ", v.flEndY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICRA_NAV_MESSAGE_START_END_POINT_H
