// Generated by gencpp from file icra_nav/start_end_srv.msg
// DO NOT EDIT!


#ifndef ICRA_NAV_MESSAGE_START_END_SRV_H
#define ICRA_NAV_MESSAGE_START_END_SRV_H

#include <ros/service_traits.h>


#include <icra_nav/start_end_srvRequest.h>
#include <icra_nav/start_end_srvResponse.h>


namespace icra_nav
{

struct start_end_srv
{

typedef start_end_srvRequest Request;
typedef start_end_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct start_end_srv
} // namespace icra_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_nav::start_end_srv > {
  static const char* value()
  {
    return "276ffc8a587afd4c10db6438819f07e3";
  }

  static const char* value(const ::icra_nav::start_end_srv&) { return value(); }
};

template<>
struct DataType< ::icra_nav::start_end_srv > {
  static const char* value()
  {
    return "icra_nav/start_end_srv";
  }

  static const char* value(const ::icra_nav::start_end_srv&) { return value(); }
};


// service_traits::MD5Sum< ::icra_nav::start_end_srvRequest> should match 
// service_traits::MD5Sum< ::icra_nav::start_end_srv > 
template<>
struct MD5Sum< ::icra_nav::start_end_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_nav::start_end_srv >::value();
  }
  static const char* value(const ::icra_nav::start_end_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_nav::start_end_srvRequest> should match 
// service_traits::DataType< ::icra_nav::start_end_srv > 
template<>
struct DataType< ::icra_nav::start_end_srvRequest>
{
  static const char* value()
  {
    return DataType< ::icra_nav::start_end_srv >::value();
  }
  static const char* value(const ::icra_nav::start_end_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_nav::start_end_srvResponse> should match 
// service_traits::MD5Sum< ::icra_nav::start_end_srv > 
template<>
struct MD5Sum< ::icra_nav::start_end_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_nav::start_end_srv >::value();
  }
  static const char* value(const ::icra_nav::start_end_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_nav::start_end_srvResponse> should match 
// service_traits::DataType< ::icra_nav::start_end_srv > 
template<>
struct DataType< ::icra_nav::start_end_srvResponse>
{
  static const char* value()
  {
    return DataType< ::icra_nav::start_end_srv >::value();
  }
  static const char* value(const ::icra_nav::start_end_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_NAV_MESSAGE_START_END_SRV_H
