(cl:in-package icra_nav-srv)
(cl:export '(FLPATHSTARTX-VAL
          FLPATHSTARTX
          FLPATHSTARTY-VAL
          FLPATHSTARTY
          FLPATHENDX-VAL
          FLPATHENDX
          FLPATHENDY-VAL
          FLPATHENDY
          VFCONSTRAINTPOSITIONX-VAL
          VFCONSTRAINTPOSITIONX
          VFCONSTRAINTPOSITIONY-VAL
          VFCONSTRAINTPOSITIONY
          FLCONSTRAINTVELOCITY-VAL
          FLCONSTRAINTVELOCITY
          BOSUCCESS-VAL
          BOSUCCESS
))