(cl:in-package icra_nav-srv)
(cl:export '(VFPATHPOSITIONX-VAL
          VFPATHPOSITIONX
          VFPATHPOSITIONY-VAL
          VFPATHPOSITIONY
          VFCONSTRAINTPOSITIONX-VAL
          VFCONSTRAINTPOSITIONX
          VFCONSTRAINTPOSITIONY-VAL
          VFCONSTRAINTPOSITIONY
          BOSUCCESS-VAL
          BOSUCCESS
))