; Auto-generated. Do not edit!


(cl:in-package roborts_msgs-msg)


;//! \htmlinclude LocalPlannerGoal.msg.html

(cl:defclass <LocalPlannerGoal> (roslisp-msg-protocol:ros-message)
  ((route
    :reader route
    :initarg :route
    :type nav_msgs-msg:Path
    :initform (cl:make-instance 'nav_msgs-msg:Path)))
)

(cl:defclass LocalPlannerGoal (<LocalPlannerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LocalPlannerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LocalPlannerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name roborts_msgs-msg:<LocalPlannerGoal> is deprecated: use roborts_msgs-msg:LocalPlannerGoal instead.")))

(cl:ensure-generic-function 'route-val :lambda-list '(m))
(cl:defmethod route-val ((m <LocalPlannerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader roborts_msgs-msg:route-val is deprecated.  Use roborts_msgs-msg:route instead.")
  (route m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LocalPlannerGoal>) ostream)
  "Serializes a message object of type '<LocalPlannerGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'route) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LocalPlannerGoal>) istream)
  "Deserializes a message object of type '<LocalPlannerGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'route) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LocalPlannerGoal>)))
  "Returns string type for a message object of type '<LocalPlannerGoal>"
  "roborts_msgs/LocalPlannerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LocalPlannerGoal)))
  "Returns string type for a message object of type 'LocalPlannerGoal"
  "roborts_msgs/LocalPlannerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LocalPlannerGoal>)))
  "Returns md5sum for a message object of type '<LocalPlannerGoal>"
  "c9406e3970e812deed30e863deddb6d6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LocalPlannerGoal)))
  "Returns md5sum for a message object of type 'LocalPlannerGoal"
  "c9406e3970e812deed30e863deddb6d6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LocalPlannerGoal>)))
  "Returns full string definition for message of type '<LocalPlannerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%nav_msgs/Path route~%~%================================================================================~%MSG: nav_msgs/Path~%#An array of poses that represents a Path for a robot to follow~%Header header~%geometry_msgs/PoseStamped[] poses~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LocalPlannerGoal)))
  "Returns full string definition for message of type 'LocalPlannerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%nav_msgs/Path route~%~%================================================================================~%MSG: nav_msgs/Path~%#An array of poses that represents a Path for a robot to follow~%Header header~%geometry_msgs/PoseStamped[] poses~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LocalPlannerGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'route))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LocalPlannerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LocalPlannerGoal
    (cl:cons ':route (route msg))
))
